version: "2"

services:
  surah:
    build: ./surah
    container_name: surah
    volumes:
      - "./surah:/src/app"
    ports:
      - "5001:5001"
    command: "npm run start"

  db:
    image: postgres
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  users:
    build: ./users
    container_name: users
    volumes:
      - "./users:/src/app"
    ports:
      - "5003:5003"
    command: "npm run start"

  gateway:
    build: ./gateway
    container_name: gateway
    volumes:
      - "./gateway:/src/app"
    ports:
      - "80:80"
    links:
      - surah
      - juz
      # - users
    environment:
      - JUZ_URL=http://juz:5001
      - SURAH_URL=http://surah:5002
    command: "npm run start"
